project:
  type: website
  output-dir: docs

website:
  title: "TSO Monitor"
  
format:
  dashboard-html:
    theme: cosmo
    orientation: columns
    embed-resources: true
    css: styles.css
    page-layout: full     # Add this line
    margin-width: 0px    # Add this line