name: Publish Dashboard

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googlesheets4
            any::googledrive
            any::reactable
            any::tidyverse
            any::gt
            any::htmltools
          
      - name: Configure Google Sheets Auth
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > gs-creds.json
          echo "GOOGLE_SHEETS_AUTH_FILE=$GITHUB_WORKSPACE/gs-creds.json" >> $GITHUB_ENV
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_SHEETS_AUTH_FILE: ${{ env.GOOGLE_SHEETS_AUTH_FILE }}