name: Test and Publish Dashboard

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googlesheets4
            any::googledrive
            any::tidyverse
            
      - name: Set up Google Sheets credentials
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > gs-creds.json
          # Debug: Check file exists and first few lines (avoiding sensitive data)
          ls -l gs-creds.json
          head -n 1 gs-creds.json
        shell: bash

      - name: Setup R environment variables
        run: |
          echo "GOOGLE_SHEETS_AUTH_FILE=$GITHUB_WORKSPACE/gs-creds.json" >> $GITHUB_ENV
          # Debug: Print environment variable
          echo "Auth file location: $GOOGLE_SHEETS_AUTH_FILE"
        shell: bash

      - name: Run test script
        run: Rscript test.R
        env:
          GOOGLE_SHEETS_AUTH_FILE: ${{ env.GOOGLE_SHEETS_AUTH_FILE }}