name: Publish Dashboard

on:
  push:
    branches: main
    paths:
      - 'index.qmd'
      - '_quarto.yml'
  schedule:
    - cron: '0 0 * * *'  # Fixed cron syntax
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      # Install system dependencies needed for R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      # Install R packages with proper error handling
      - name: Install R packages
        run: |
          install.packages('remotes')
          remotes::install_cran(c(
            'gargle',
            'googledrive',
            'googlesheets4',
            'reactable',
            'tidyverse',
            'gt',
            'htmltools'
          ), dependencies = TRUE)
        shell: Rscript {0}

      # Setup Quarto
      - uses: quarto-dev/quarto-actions/setup@v2
          
      # Configure Google Sheets credentials
      - name: Set up Google Sheets credentials
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > gs-creds.json
          # Debug: verify file exists and is valid JSON (without showing content)
          if [ -f gs-creds.json ]; then
            echo "Credentials file created"
            if jq empty gs-creds.json 2>/dev/null; then
              echo "Credentials file contains valid JSON"
            else
              echo "ERROR: Invalid JSON in credentials file"
              exit 1
            fi
          else
            echo "ERROR: Credentials file not created"
            exit 1
          fi
          
      # Render and Publish
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_SHEETS_AUTH_FILE: gs-creds.json