name: Test Auth

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Check Credentials
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > gs-creds.json
          if [ -s gs-creds.json ]; then
            echo "Credentials file created and not empty"
            echo "File size: $(wc -c < gs-creds.json) bytes"
          else
            echo "Credentials file is empty"
          fi