name: Test R Google Sheets

on:
  workflow_dispatch:

jobs:
  test-r-sheets:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libharfbuzz-dev \
            libfribidi-dev

      # Install R packages with proper error handling
      - name: Install R packages
        run: |
          install.packages('remotes')
          remotes::install_cran(c(
            'gargle',
            'googledrive',
            'googlesheets4'
          ), dependencies = TRUE)
        shell: Rscript {0}
          
      - name: Set up Google Sheets credentials
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > gs-creds.json
          
      - name: Test Google Sheets connection
        run: Rscript test_sheets.R
        env:
          GOOGLE_SHEETS_AUTH_FILE: gs-creds.json