name: Test Credentials

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Test Google Sheets credentials format
        run: |
          # Write credentials to a temp file
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > test-creds.json
          
          # Check if it's valid JSON (without exposing content)
          if jq empty test-creds.json 2>/dev/null; then
            echo "✓ Credentials are valid JSON"
            echo "✓ Found the following keys:"
            jq -r 'keys[]' test-creds.json | sed 's/^/  - /'
            
            # Verify it's a service account
            if [ "$(jq -r '.type' test-creds.json)" = "service_account" ]; then
              echo "✓ Confirmed service account type"
              echo "✓ Project ID: $(jq -r '.project_id' test-creds.json)"
              echo "✓ Client email: $(jq -r '.client_email' test-creds.json)"
            else
              echo "✗ Not a service account"
              exit 1
            fi
          else
            echo "✗ Invalid JSON format"
            exit 1
          fi
          
          # Clean up
          rm test-creds.json