name: Credentials Test Only

on:
  workflow_dispatch:

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Basic Credential Test
        run: |
          echo "Testing credentials file creation..."
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > gs-creds.json
          if [ -s gs-creds.json ]; then
            echo "✓ File created successfully"
            echo "✓ File size: $(wc -c < gs-creds.json) bytes"
            echo "✓ File appears to be JSON (checking format)"
            if jq empty gs-creds.json 2>/dev/null; then
              echo "✓ Valid JSON format confirmed"
            else
              echo "✗ Invalid JSON format"
            fi
          else
            echo "✗ File is empty"
          fi